name: Build Mod
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Build Now
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Find Output Jar
        id: findjar
        run: |
          output="$(find fabricWrapper/build/libs/ ! -name "*-dev.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "jarname=$output" >> $GITHUB_OUTPUT

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.findjar.outputs.jarname }}
          path: fabricWrapper/build/libs/*.jar